#!/usr/bin/env ruby
#Frozen_String_Literal: true
$-v = nil

abort "#{RUBY_ENGINE.capitalize} #{RUBY_VERSION} is not supported! Please use Ruby 2.4+" if RUBY_VERSION.split(?.).first(2).join.to_i < 24
abort "This program is written only for Linux!" unless /linux/ === RUBY_PLATFORM

Kernel.class_exec { define_method(:then) { | &b | b === self } } unless Kernel.respond_to?(:then)
String.class_exec { define_method(:delete_suffix) { |arg| slice(-arg.length..-1) == arg ? slice(0...length - arg.length) : itself } } unless String.respond_to?(:delete_suffix)

GC.start(full_mark: true, immediate_sweep: true)

def main(clear: false, refresh: 50.0)
	get_swap_usage = proc { IO.readlines('/proc/swaps').drop(1).map! { |x| x &.split &.[](3).to_i }.sum.fdiv(1024) }
	get_disk_status = proc { |partition| IO.foreach('/proc/diskstats').find { |x| x.split[2] == partition } &.split.to_a[11].to_i }
	refresh /= 1000.0

	get_cpu_usage = proc do
		data = IO.foreach('/proc/stat').first.split.map!(&:to_f)
		Kernel.sleep(refresh)
		prev_data = IO.foreach('/proc/stat').first.split.map!(&:to_f)
		%w(user nice sys idle iowait irq softirq steal).each_with_index { |el, ind| binding.eval("@#{el}, @prev_#{el} = #{data[ind + 1]}, #{prev_data[ind + 1]}") }
		previdle, idle = @prev_idle + @prev_iowait, @idle + @iowait
		totald = idle + (@user + @nice + @sys + @irq + @softirq + @steal) - previdle.+(@prev_user + @prev_nice + @prev_sys + @prev_irq + @prev_softirq + @prev_steal)
		totald.-(idle - previdle)./(totald).*(100)
	end

	n, cp = Dir['/sys/class/leds/input[0-9]*::numlock/brightness'], File.readable?('/proc/cpuinfo')
	c, sw = Dir['/sys/class/leds/input[0-9]*::capslock/brightness'], File.readable?('/proc/swaps')
	s, st = Dir['/sys/class/leds/input[0-9]*::scrolllock/brightness'], File.readable?('/proc/stat') && File.readable?('/proc/mounts')

	fail Errno::EACCES unless [n, c, s].all? { |x| x.all? { |y| File.owned?(y) } }

	puts "\e[1;31mUnreadable /proc/cpuinfo\e[0m" unless cp
	puts "\e[1;31mUnreadable /proc/swaps\e[0m" unless sw
	puts "\e[1;31mUnreadable /proc/stat or /proc/mounts.\e[0m" unless st

	root_partition = st ? IO.foreach('/proc/mounts').detect { |x| x.split[1] == ?/ }.to_s.split[0].to_s.split(?/).to_a[-1] : ''
	check = -> k, l { puts l.-(k).empty? ?  k.-(l).empty? ? '' : "\e[1;32m:: New LED\e[0m #{k.-(l).join(', ')}" : "\e[1;33m:: Removed LED\e[0m #{l.-(k).join(', ')}" }

	if (cp || sw || st)
		unless clear
			puts "\e[38;5;33mStarted Monitoring #{"CPU Usage [ \e[38;5;70mNumlock\e[38;5;33m ], " if cp}#{"Swap Usage [ \e[38;5;70mCaps Lock\e[38;5;33m ], " if sw}#{"Disk IO [ \e[38;5;70mScroll Lock\e[38;5;33m ]\e[0m" if st}".delete_suffix(', ')
			puts "\e[38;5;196mRefreshing every #{refresh * 1000} millisecond#{ refresh * 1000 != 1 ? ?s : '' }\e[0m"

			while true
				begin
					cp && get_cpu_usage.call > 75 ? n.each { |x| IO.write(x, 1) unless IO.read(x).to_i == 1 } : n.each { |x| IO.write(x, 0) unless IO.read(x).to_i == 0 }
					sw && get_swap_usage.call > 0 ? c.each { |x| IO.write(x, 1) unless IO.read(x).to_i == 1 } : c.each { |x| IO.write(x, 0) unless IO.read(x).to_i == 0 }
					st && get_disk_status.(root_partition) > 0 ? s.each { |x| IO.write(x, 1) unless IO.read(x).to_i == 1 } : s.each { |x| IO.write(x, 0) unless IO.read(x).to_i == 0 }
				rescue StandardError
					puts "\e[1;36mSkipped #{$!.to_s.split(' - ').to_a[-1]}\e[0m"
				end

				Dir['/sys/class/leds/input[0-9]*::numlock/brightness'].tap { |x| check.(x, n)  || n.replace(x) unless x == n }
				Dir['/sys/class/leds/input[0-9]*::capslock/brightness'].tap { |x| check.(x, c)  || c.replace(x) unless x == c }
				Dir['/sys/class/leds/input[0-9]*::scrolllock/brightness'].tap { |x|  check.(x, s)  || s.replace(x) unless x == s }
			end
		else
			n.each { |x| IO.write(x, 0) unless IO.read(x).to_i.zero? } if cp
			c.each { |x| IO.write(x, 0) unless IO.read(x).to_i.zero? } if sw
			s.each { |x| IO.write(x, 0) unless IO.read(x).to_i.zero? } if st
		end
	end
	nil
end

args = ARGV.join(?=).split(?-).reject(&:empty?)

query = proc { |a, d = 0| args.find { |x| x[a] }.to_s.split(?=)[-1].then { |x| x ? x : d } }

if ARGV.any? { |x| x[/(^\-\-help+$)|(^\-h+$)/] }
	puts <<~EOF
		\e[38;5;196m#{Process.argv0} Lets you monitor your system CPU, Swap and IO through keyboard lights.

		\e[38;5;200mLights:
			\e[0;32mNum Lock LED => On when CPU Usage > 75%
			\e[0;32mCaps Lock LED => On when Swap is in Use
			\e[0;32mScroll Lock LED => On when Disk that has / is Busy

		\e[38;5;200m#{Process.argv0} Arguments:
			\e[38;5;190m1.#{Process.argv0} --help                   This help section
			2.#{Process.argv0} --refresh=n/ -r=n        Refresh time specified in milliseconds.
                                                                  [Default: 50]
		\e[38;5;200m#{Process.argv0} Arguments Example:
			\e[38;5;12m#{Process.argv0} --refresh=1000
			#{Process.argv0} --refresh 1000\e[0m
	EOF

	exit 0
end

refresh = query.(/(^r\=[0-9\.]*=?+$)|(^refresh\=[0-9\.]*=?+$)/, 50).to_f.then { |x| x < 1 ? 1 : x }

begin
	main(refresh: refresh)
rescue Interrupt, SignalException, SystemExit
	puts "\n\e[38;5;45mBye!\e[0m"
rescue Errno::EACCES
	puts "\n\e[1;31mPermission Denied. Try Running #{$0} as Root.\e[0m" unless system('notify-send', ":: #{$0}: Permission Denied. Try Running #{$0} as Root.")
rescue Exception
	puts "Hi, #{File.basename($0)} crashed! Reason:\n#{$!.backtrace.join(?\n)}"
ensure
	main(clear: true) rescue nil
end
