#!/usr/bin/env bash

sudo rmmod uvcvideo
sudo modprobe v4l2loopback devices=4
sleep 1
sudo ffmpeg -f x11grab -r 30 -i :0.0+0.0 -s 1920x1080 -threads 0 -vcodec rawvideo -pix_fmt yuv420p -f pulse -ac 2 -f v4l2 /dev/video1
