#!/usr/bin/env bash

sudo rmmod uvcvideo
sudo modprobe v4l2loopback devices=4
sleep 1
sudo ffmpeg -f x11grab -r 15 -s 1920x1024 -i :0.0+0.0 -vcodec rawvideo -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video0 1>/dev/null &
sudo modprobe uvcvideo
